import { skipWaiting, clientsClaim } from 'workbox-core'
import { precacheAndRoute } from 'workbox-precaching'
import { handlePeriodicSyncReg } from './registerPeriodicSync'

// self.__WB_MANIFEST is the precache manifest generated by the plugin
precacheAndRoute(self.__WB_MANIFEST)

skipWaiting()
clientsClaim()

self.addEventListener('activate', (event) => {
  handlePeriodicSyncReg(event.target.registration)
})
